### ISSUE TITLE
Winget show theres an new version but it's up to date.

### ISSUE THREAD

**Issue by akacantr** [InsertX2k/temp_cleaner_gui#11]
When i run the command winget upgrade to view available updates TCG's version number for installed version is shown as "> 6.8" and the latest version number is "6.9-stable" which is my version that already installed.

**Comment by InsertX2k** [comment]
> When i run the command winget upgrade to view available updates TCG's version number for installed version is shown as "> 6.8" and the latest version number is "6.9-stable" which is my version that already installed.

It is a common issue with Winget even with other software that aren't installed from it, To fix this you have to uninstall your current version of Temp_Cleaner GUI and install the Winget version using this command:

```bat
winget install Ziad.TCG
```
